language: node_js
node_js: 10
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  directories:
    - ~/.cache
    - ~/.npm
install:
  - . npm.sh ci
script:
  - . npm.sh run ci
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  on:
    branch: master
